### ISSUE TITLE
Astor display verion is incorrect

### ISSUE THREAD

**Issue by Ingvord** [tango-controls/Astor#11]
See screenshot:

![version_bug](https://cloud.githubusercontent.com/assets/11678364/25479120/0c7cc13a-2b44-11e7-8375-136de318d29e.png)

with the blue rectangle actual version number is highlighted; the red ones - displayed version.

Solution would be to get the actual version from the maven, for instance consider this article: [link](http://blog.soebes.de/blog/2014/01/02/version-information-into-your-appas-with-maven/)

**Comment by Pascal-Verdier** [comment]
Fixed.
