### ISSUE TITLE
remote login

### ISSUE THREAD

**Issue by PhilLAL** [tango-controls/Astor#15]
Hi Pascal,
I see in the [dedicated doc page](https://tango-controls.readthedocs.io/en/dev/tools-and-extensions/astor/add_host.html) we need to `Start a new remote loggin session to start it from host popup menu`.

When I right-click on a new host I just created, and select `remote login`, I'm asked for a password.
This is not the password from the user which starts astor, who's password is asked?
Regards

**Comment by Pascal-Verdier** [comment]
It is the password to log on the remote host.
The loggin user is set as property using File/Ctrl Sysytem preferences menu
![image](https://user-images.githubusercontent.com/19665928/52325711-58c47e00-29e6-11e9-98db-e114f940ff4e.png)

**Comment by PhilLAL** [comment]
Thank you very much Pascal! :)
